---
title: "Chapter Five"
author: "NAME HERE"
date: "9/25/2017"
header-includes:
   - \usepackage{bbm}
   - \usepackage{bm}
   - \newcommand{\infmat}{\bm{\mathcal{J}}}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Exercise One
#### Question
Consider the single response variable $Y$ with $Y \sim \text{Bin}(n, \pi)$.

#### Solution
**(a)**: Find the Wald statistic $(\hat{\pi} - \pi)^T\infmat(\hat{\pi} - \pi)$, where $\hat{\pi}$ is the maximum likelihood estimator of $\pi$ and $\infmat$ is the information.

**(b)**: Verify that the Wald statistic is the same as the score statistic $\bm{U}^T\infmat^{-1}\bm{U}$ in this case (see Example 5.22).

**(c)**: Find the deviance
$$
2[l(\hat{\pi};y) - l(\pi; y)].
$$

**(d)**: For large samples, both the Wald/score statistic and the deviance approximatley have the $\chi^2(1)$ distribution. For $n= 10$ and $y = 3$, use both statistics to assess the adequacy of the models:

(1) $\pi = 0.1$
(1) $\pi = 0.3$
(3) $\pi = 0.5$

Do the two statistics lead to the same conclusions?

## Exercise Two
#### Question
Consider a random sample $Y_1, ..., Y_N$ with the exponential distributon
$$
f(y_i, \theta_i) = \theta_i\exp(-y_i\theta_i)
$$
Derive the deviance by comparing the maximal model with different values for $\theta_i$ for each $Y_i$ and the model with $\theta_i = \theta$ for all $i$.

#### Solution



## Exercise Four
#### Question
For the leukemia survival data in 4.2:

#### Solution
**(a)**: Use the Wald statistic to obtain an approximate 95\% confidence interval for  the paramter $\beta_1$.

**(b)**: By comparing the deviances for two appropriate models, test the null hypothesis $\beta_2 = 0$ against the alternative hypothesis $\beta_2 \neq 0$. What can you conclude about the use of the initial white blood cell count as a predictor of survival time.