---
title: "Chapter Six"
author: "NAME HERE"
date: "10/2/2017"
header-includes:
   - \usepackage{bbm}
   - \usepackage{bm}
   - \newcommand{\infmat}{\bm{\mathcal{J}}}
   - \usepackage{booktabs}
   - \usepackage{multirow}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Exercise Four
#### Question
It is well known that the concentration of cholesterol in blood serum increase with age, but it is less clear whether cholesterol level is also associated with body weight. The table below shows for thirty women serum cholesterol, (millimoles per liter), age (years) and body mass index (weight divided by height squared, where weight was measured in kilograms and height in meters). Use multiple regression to test whether serum cholesterol is associated with body mass index when age is already included in the model.

\begin{center}
\begin{tabular}{@{}ccccccc@{}}
\toprule
CHOL & Age & BMI  &  & CHOL & Age & BMI  \\ \midrule
5.94 & 52  & 20.7 &  & 6.48 & 65  & 26.3 \\
4.71 & 46  & 21.3 &  & 8.83 & 76  & 22.7 \\
5.86 & 51  & 25.4 &  & 5.1  & 47  & 21.5 \\
6.52 & 44  & 22.7 &  & 5.81 & 43  & 20.7 \\
6.8  & 70  & 23.9 &  & 4.65 & 30  & 18.9 \\
5.23 & 33  & 24.3 &  & 6.82 & 58  & 23.9 \\
4.97 & 21  & 22.2 &  & 6.28 & 78  & 24.3 \\
8.78 & 63  & 26.2 &  & 5.15 & 49  & 23.8 \\
5.13 & 56  & 23.3 &  & 2.92 & 36  & 19.6 \\
6.74 & 54  & 29.2 &  & 9.27 & 67  & 24.3 \\
5.95 & 44  & 22.7 &  & 5.57 & 42  & 22   \\
5.83 & 71  & 21.9 &  & 4.92 & 29  & 22.5 \\
5.74 & 39  & 22.4 &  & 6.72 & 33  & 24.1 \\
4.92 & 58  & 20.2 &  & 5.57 & 42  & 22.7 \\
6.69 & 58  & 24.4 &  & 6.25 & 66  & 27.3 \\ \bottomrule
\end{tabular}
\end{center}

#### Solution

## Exercise Five
#### Question
The table below shows plasma inorganic phospate levels (mg/dl) one hour after a standard glucose tolerance test for obese subjects, with or without hyperinsulinemia, and controls (data from Jones 1987).
\begin{center}
\begin{tabular}{@{}ccc@{}}
\toprule
Hyperinsulinemic & Non-hyperinsulinemic & Controls \\
obese            & obese                &          \\ \midrule
2.3              & 3.0                  & 3.0      \\
4.1              & 4.1                  & 2.6      \\
4.2              & 3.9                  & 3.1      \\
4.0              & 3.1                  & 2.2      \\
4.6              & 3.3                  & 2.1      \\
3.8              & 3.3                  & 2.8      \\
5.2              & 3.9                  & 3.4      \\
3.1              &                      & 2.9      \\
3.7              &                      & 2.6      \\
3.8              &                      & 3.1      \\
                 &                      & 3.2      \\ \bottomrule
\end{tabular}
\end{center}

#### Solution
**(a)**: Perform a one-factor analysis of variance to test the hypothesis that there are no mean differences among the three groups. What conclusions ca you draw?

**(b)**: Obtain a 95% confidence interval for the difference in means between the two obese groups.

**(c)**: Using an appropriate model, examine the stqndardized residuals for all the observations to look for any systematic effects and to check the Normality assumption.


## Exercise Seven
#### Question
For the balanced data in the table below (Table 6.10), the analyses in Section 6.4.2 showed that the hypothesis tests were independent. An alternative specification of the design matrix for the saturated model (6.9) with the corner point constraints $\alpha_1 = \beta_1 = (\alpha\beta)_{12} = (\alpha\beta)_{21} = (\alpha\beta)_{31} = 0$. so that
$$\bm{\beta} = \begin{bmatrix}
\mu\\ \alpha_2\\ \alpha_3\\ \beta_2\\ (\alpha\beta)_{22} \\(\alpha\beta)_{32} \end{bmatrix} \quad \text{and} \quad
\bm{X} = \begin{bmatrix}
1 & -1 & -1 & -1 & 1  & 1  \\
1 & -1 & -1 & -1 & 1  & 1  \\
1 & -1 & -1 & 1  & -1 & -1 \\
1 & -1 & -1 & 1  & -1 & -1 \\
1 & 1  & 0  & -1 & -1 & 0  \\
1 & 1  & 0  & -1 & -1 & 0  \\
1 & 1  & 0  & 1  & 1  & 0  \\
1 & 1  & 0  & 1  & 1  & 0  \\
1 & 0  & 1  & -1 & 0  & -1 \\
1 & 0  & 1  & -1 & 0  & -1 \\
1 & 0  & 1  & 1  & 0  & 1  \\
1 & 0  & 1  & 1  & 0  & 1 
\end{bmatrix},$$
where the columns of $\bm{X}$ corresponding to the terms $(\alpha\beta)_{jk}$ are the products of columns corresponding to terms $\alpha_j$ and $\beta_k$.

\begin{center}
\begin{tabular}{cccc}
\hline
          & \multicolumn{3}{c}{Levels of Factor B}                                 \\ \cline{2-4} 
Levels of & \multirow{2}{*}{$B_1$} & \multirow{2}{*}{$B_2$} & \multirow{2}{*}{Total} \\
Factor A  &                       &                       &                        \\ \hline
$A_1$      & 6.8, 6.6              & 5.3, 6.1              & 24.8                   \\
$A_2$      & 7.5, 7.4              & 7.2, 6.5              & 28.6                   \\
$A_3$      & 7.8, 9.1              & 8.8, 9.1              & 34.8                   \\ \hline
Total     & 45.2                  & 43                    & 88.2                   \\ \hline
\end{tabular} $\quad$ \begin{tabular}{llrrr}
\hline
Source of    & \multicolumn{1}{c}{Degrees of} & \multicolumn{1}{c}{Sum of}  & \multicolumn{1}{c}{Mean}   & \multicolumn{1}{c}{}  \\
variation    & \multicolumn{1}{c}{freedom}    & \multicolumn{1}{c}{Squares} & \multicolumn{1}{c}{square} & \multicolumn{1}{c}{F} \\ \hline
Mean         & 1                              & 648.2700                    &                            &                       \\
Levels of A  & 2                              & 12.7400                     & 6.3700                     & 25.82                 \\
Levels of B  & 1                              & 0.4033                      & 0.4033                     & 1.63                  \\
Interactions & 2                              & 1.2067                      & 0.6033                     & 2.45                  \\
Residual     & 6                              & 1.4800                      & 0.2467                     &                       \\ \hline
Total        & 12                             & 664.1000                    &                            &                       \\ \hline
\end{tabular}
\end{center}

#### Solution
**(a)**: Show that $\bm{X}^T\bm{X}$ has the block diagonal form described in Section 6.2.5. Fit the model (6.9) and also the models (6.10) and (6.12) and verify that the results in the second table above (Table 6.12) are the same for this specification of $\bm{X}$. 

**(b)**: Show that the estimates for the means of the subgroup with the treatments $A_3$ and $B_2$ for two different models are the same as the values given at the end of Section 6.4.2.