---
title: "Chapter Four"
author: "NAME HERE"
header-includes:
   - \usepackage{bbm}
   - \usepackage{bm}
output:
  pdf_document:
    keep_tex: yes
    
tables: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise One
#### Question
The data in Table the table below show the numbers of cases of AIDS in Australia by date of diagnosis for successive 3-months periods from 1984 to 1988. (Data from National Centre for HIV Epidemiology and Clinical Research 1994.)

In this early phase of the epidemic, the numbers of cases seemed to be increasing exponentially.

\begin{center}
\begin{tabular}{@{}crrrr@{}}
\toprule
     & \multicolumn{4}{c}{Quarter} \\
Year & 1     & 2     & 3    & 4    \\ \midrule
1984 & 1     & 6     & 16   & 23   \\
1985 & 27    & 39    & 31   & 30   \\
1986 & 43    & 51    & 63   & 70   \\
1987 & 88    & 97    & 91   & 104  \\
1988 & 110   & 113   & 149  & 159  \\ \bottomrule
\end{tabular}
\end{center}

#### Solutions
**(a)**: Plot the number of cases $y_i$ against time period $i$ ($i = 1,...,20$).

**(b)**: A possible model is the Poisson distribution with parameter $\lambda_i = i^\theta$, or equivelantly
$$
\log\lambda_i = \theta\log i.
$$
Plot $\log y_i$ against $\log i$ to examine this model.

**(c)**: Fit a gneralized linear model to these data using the Poisson distribution, the log-link function and the equation
$$
g(\lambda_i) = \log\lambda_i = \beta_1 + \beta_2x_i,
$$
where $x_i = \log i$. Firstly, do this from first principles, working out expressions for the weight matrix $\bm{W}$ and other terms needed for the iterative equation
$$
\bm{X}^T\bm{WXb}^{(m)} = \bm{X}^T\bm{Wz}
$$
and using software which can perform matrix operations to carry out the calculations.

**(d)**: Fit the model in (c) using statistical software which can perform Poisson regression. Compare the results with those obtained in (c).

\pagebreak

## Exercise Two
#### Question
The data in the table below are times to death, $y_i$, in weeks from diagnosis and $\log_{10}$(initial white blood cell count), $x_i$, for seventeen patients suffering from leukemia. (This is Example U from Cox and Snell 1981.)

\begin{center}
% Please add the following required packages to your document preamble:
% \usepackage{booktabs}
\begin{table}[]
\centering
\caption{My caption}
\label{my-label}
\begin{tabular}{@{}crrrrrrrrr@{}}
\toprule
$y_i$ & 65   & 156  & 100  & 134  & 16   & 108  & 121  & 4    & 39   \\
$x_i$ & 3.36 & 2.88 & 3.63 & 3.41 & 3.78 & 4.02 & 4.00 & 4.23 & 3.73 \\
      &      &      &      &      &      &      &      &      &      \\
$y_i$ & 143  & 56   & 26   & 22   & 1    & 1    & 5    & 65   &      \\
$x_i$ & 3.85 & 3.97 & 4.51 & 4.54 & 5.00 & 5.00 & 4.72 & 5.00 &      \\ \bottomrule
\end{tabular}
\end{table}
\end{center}

#### Solutions
**(a)**: Plot $y_i$ against $x_i$. Do the data show any trends?

**(b)**: A possible specification for $E(Y)$ is
$$
\text{E}(Y_i) = \exp(\beta_1 + \beta_2x_i),
$$
which can ensure all E$(Y)$ is non-negative for lall values of the paramaters and all values of $x$. Which link functio is appropriate in this case?

**(c)**: The Exponential distribution is ofte used to describe survival times. The probability distribution is $f(y; \theta) = \theta e^{-y\theta}$. This is a sepcial case of the Gamma distribution with shape parameters $\phi = 1$ (see Exercise 3.12(a)). Show that E$(Y) = 1/\theta$ and var$(Y) = 1/\theta^2$.

**(d)**: Fit a model with the equation for E$(Y_i)$ given in (b) and the Exponential distribution using appropriate statistical software.

**(e)**: For the model fitted in (d), compare the observed values $y_i$, and fitted values $\hat{y_i} = \exp(\hat{\beta_1} + \hat{\beta_2}x_i),$ and use the standardized residuals $r_i = (y_i - \hat{y_i})/\hat{y_i}$ to investigate the adequacy of the model. (Note: \$hat{y_i}$ is used as the denominator of $r_i$ because it is an estimate of the standard deviation of $Y_i$--see (c) above.)