\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Chapter One},
            pdfauthor={Ryan B. Honea},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Chapter One}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{Ryan B. Honea}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \date{}
  \predate{}\postdate{}


\begin{document}
\maketitle

\subsection{Exercise One}\label{exercise-one}

\paragraph{Question}\label{question}

As in Example 1.1, suppose that one machine produces rods with diameters
normally distributed with mean 27 mm and standard deviation 1.53 mm, so
that 2.5 percent of the rods have diameter 30 mm or more. A second
machine is known to produce rods with diameters normally distributed
with mean 24 mm and 2.5 percent of rods it produces have diameter 30 mm
or more. What is the standard deviation of rods produced by the second
machine?

\paragraph{Solution}\label{solution}

We will solve this by utilizing the formula for z-score. The upper 2.5\%
of data is located 1.96 standard deviations to the right of the mean or
at \(z = 1.96\). The formula for z-score is \[
        z_x = \frac{x - \mu}{\sigma}
    \] where \(x\) is the value being considered. In this case, we have
\[
        1.96 = \frac{30 - 24}{\sigma} \rightarrow \sigma = \frac{30 - 24}{1.96}
        \rightarrow \sigma \approx 3.06
    \] So, the standard deviation is approximately 3.06.

\subsection{Exercise Two}\label{exercise-two}

\paragraph{Question}\label{question-1}

In a group of 145 patients admitted to a hospital with a stroke, weekly
alcohol consumption in standard units had a mean of 17 and a standard
deviation of 22. Explain why their alcohol consumption does not follow a
normal distribution. Is this finding surprising?

\paragraph{Solution}\label{solution-1}

In a normal distribution, approximately 68\% of the data lies between
one standard deviation from the mean. Therefore, if this group were
normally distributed, 68\% of the patents would have a weekly alcohol
consumption of -5 units to 39 units which does not make sense as -5
units is an impossible value of weekly consumption. This is likely a
right-skewed distribution which isn't altogether surprising. Though this
based on experience, I would argue the number of binge drinkers is low,
but the volume of alcohol a binge drinker might consume is enough to
skew the standard deviation.

\pagebreak

\subsection{Exercise Three}\label{exercise-three}

\paragraph{Question}\label{question-2}

Following a television campaign about the risks of smoking tobacco, the
cigarette consumption of a group of 50 smokers decreases by a mean of 5
cigarettes per day with a standard deviation of 8. Explain why the
reasoning of Exercise 2 cannot be used to show that this distribution is
not normal.

\paragraph{Solution}\label{solution-2}

In this case, we aren't sure of the current amount of cigarettes our
sample smokes. The argument of Exercise 2 relies on knowing a minimum
where in this case a smokers habit could change from between -13 to +3
cigarettes a day. Even out to three standard deviations, it's completely
reasonable to believe that a smoker might change -29 and +19 cigarettes
a day in the most extreme of cases. There is no evidence to suggest that
it isn't normal.

\subsection{Exercise Four}\label{exercise-four}

\paragraph{Question}\label{question-3}

In section 1.3, we pointed out that 5 tosses of a coin would never
provide evidence against the hypothesis that a coin was fair (equally
likely to fall heads or tails) at a conventional 5 percent significance
level. What is the least number of tosses needed to provide such
evidence using a two-tail test, and what is then the exact \(P\)-value.

\paragraph{Solution}\label{solution-3}

Following the logic of section 1.3 which takes the most extreme case
(which would give the least number of tosses needed), we are interested
in finding the probability that all the tosses are either all heads or
all tails. So, we want to find \(x\) where \[
        P =     .05 >= 2 * (0.5)^x
    \] Note that this is essentially a two-tailed test. \[
        .025 >= (0.5)^x \rightarrow x = \log_{0.5}(0.025) \approx 5.32
    \]

To find the minimum number of tosses, we take the ceiling of that result
which is six tosses. The exact \(P\)-value it would give is
\(P = 2 * (0.5)^6 = .03125\).

\pagebreak

\subsection{Exercise Five}\label{exercise-five}

\paragraph{Question}\label{question-4}

A biased coin is such that Pr(heads) = 2/3. If this coin is tossed, the
least number of times calculated in Exercise 1.4, what is the
probability of an error of the second kind associated with the 5 percent
significance level? What is the power of the test? Does the discrete
nature of possible \(P\)-values cause any problems in calculating the
power?

\paragraph{Solution}\label{solution-4}

Consider this a two-tailed binomial test where \(p\) determines the
probability of flipping a heads. Then the tests are \(H_0: p = .5\) and
\(p: \mu \neq .5\). The sample probability interval in which we wouldn't
reject the null hypothesis for this test would therefore come from the
binomial confidence interval equation \[
        p \pm z_{\alpha/2}\sqrt{\frac{1}{n}p(1-p)} \rightarrow
        .5 \pm 1.65\sqrt{\frac{1}{6}{.5*.5}} \rightarrow
        (.163,.834)
    \] In terms of coins flipped, that interval then means that we
should observe at least 1 head and at most 5 heads in order to not
reject the null hypothesis. If the probability that heads is flipped is
actually \(2/3\), then we can use the binomial cumulative distribution
to find the probability that we will fail to reject the null hypothesis
which would result in type two error. I use R to determine this value.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pbinom}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DataTypeTok{size =} \DecValTok{6}\NormalTok{, }\DataTypeTok{prob =}\NormalTok{ (}\DecValTok{2}\OperatorTok{/}\DecValTok{3}\NormalTok{)) }\OperatorTok{-}\StringTok{ }\KeywordTok{pbinom}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DataTypeTok{size =} \DecValTok{6}\NormalTok{, }\DataTypeTok{prob =}\NormalTok{ (}\DecValTok{2}\OperatorTok{/}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9108368
\end{verbatim}

The Type II error therefore is approximately .911 while the power of the
test is .089 which is not a strong value.

The discrete nature of \(P\) here causes slight problems because the
typical method for calculating power would use the critical
probabilities which are continuous while the number of heads is
discrete. If you could observe fractions of heads, then the actual
interval of heads is \((.978, 5.004)\). That being said, binomials don't
work that way and so the current power of the test is the most accurate
result possible and not problematic.

\pagebreak

\subsection{Exercise Six}\label{exercise-six}

\paragraph{Question}\label{question-5}

If a random variable \(X_i\) is distributed N\((\mu, \sigma^2)\) and all
\(X_i\) are independent, it is well know that the variable \[
        Y = \sum^n_{i=1}X_i
    \] is distributed \(N(n\mu, n\sigma^2).\) Use this result to answer
the following:

The times in minutes a farmer takes to place any fence post are each
independently distributed N\((10,2)\). He starts placing posts at 9 a.m
one morning, and immediately after one post is placed he proceeds to
place another, continuing until he has placed 9 posts. What is the
probability that he has placed all 9 posts by (i) 10.25 a.m, (ii) 10.30
am, and (iii) 10.40 a.m?

\paragraph{Solution}\label{solution-5}

It will be easier to answer this in terms of minutes past instead of by
time. The problems will instead be considered as (i) at most 85 minutes,
(ii) at most 90 minutes, and (iii) at most 100 minutes. Based on the
information given, the minutes he completes the task in is distributed
N\((90, 18)\). For each subproblem, I will use the normal cdf in R.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pnorm}\NormalTok{(}\DecValTok{85}\NormalTok{, }\DecValTok{90}\NormalTok{, }\KeywordTok{sqrt}\NormalTok{(}\DecValTok{18}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1192964
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pnorm}\NormalTok{(}\DecValTok{90}\NormalTok{, }\DecValTok{90}\NormalTok{, }\KeywordTok{sqrt}\NormalTok{(}\DecValTok{18}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{90}\NormalTok{, }\KeywordTok{sqrt}\NormalTok{(}\DecValTok{18}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9907889
\end{verbatim}

\texttt{pnorm(x,mu,std)} calculates \(P(X < x)\) where mu is your mean
and std is your standard deviation. The answers therefore are: (i) .119,
(ii) .500, and (iii) .991

\pagebreak

\subsection{Exercise Seven}\label{exercise-seven}

\paragraph{Question}\label{question-6}

The following two sample data sets both have sample mean 6.
\[\begin{array}
{cccccccccc}
\text{Set I} & 13.9 & 2.7 & 0.8 & 11.3 & 1.3 \\
\text{Set II} & 2.7 & 8.3 & 5.2 & 7.1 & 6.7 \\
\end{array}
\]

\begin{longtable}[]{@{}cc@{}}
\toprule
\begin{minipage}[b]{0.10\columnwidth}\centering\strut
Set I\strut
\end{minipage} & \begin{minipage}[b]{0.10\columnwidth}\centering\strut
Set II\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.10\columnwidth}\centering\strut
13.9\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering\strut
2.7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\centering\strut
2.7\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering\strut
8.3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\centering\strut
0.8\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering\strut
5.2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\centering\strut
11.3\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering\strut
7.1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\centering\strut
1.3\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\centering\strut
6.7\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

If \(\mu\) is the population mean, perform for each set \(t\)-tests of
(i) \(H_0: \mu = 8\) against \(H_1: \mu \neq 8\) and (ii)
\(H_0: \mu = 10\) against \(H_1: \mu \neq 10\). Do you consider the
conclusions of the tests reasonable? Have you any reservations about
using a \(t\)-test for either of these data sets?

\paragraph{Solution}\label{solution-6}

I'll address my one reservation before performing the tests. One of the
assumptions that must be made when performing a \(t\)-test is a
reasonably large sample size. A sample size of \(5\) would not typically
be considered a large sample size. The results of the test are as
follows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SetI <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\FloatTok{13.9}\NormalTok{, }\FloatTok{2.7}\NormalTok{, }\FloatTok{0.8}\NormalTok{, }\FloatTok{11.3}\NormalTok{, }\FloatTok{1.3}\NormalTok{)}
\NormalTok{SetII <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\FloatTok{2.7}\NormalTok{, }\FloatTok{8.3}\NormalTok{, }\FloatTok{5.2}\NormalTok{, }\FloatTok{7.1}\NormalTok{, }\FloatTok{6.7}\NormalTok{)}
\NormalTok{mu_i <-}\StringTok{ }\DecValTok{8}
\NormalTok{mu_ii <-}\StringTok{ }\DecValTok{10}
\KeywordTok{t.test}\NormalTok{(SetI, }\DataTypeTok{mu =}\NormalTok{ mu_i)}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5063734
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(SetII, }\DataTypeTok{mu =}\NormalTok{ mu_i)}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1062178
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(SetI, }\DataTypeTok{mu =}\NormalTok{ mu_ii)}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2185681
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(SetII, }\DataTypeTok{mu =}\NormalTok{ mu_ii)}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0141824
\end{verbatim}

The only case where the \(P\)-value is lower than 5\% is whether SetII
is different from \(\mu = 10\) so we reject \(H_0\) in that case. All of
the others, we fail to reject the null hypothesis.

\pagebreak

\subsection{Exercise Eight}\label{exercise-eight}

\paragraph{Question}\label{question-7}

Use an available standard statistical software package, or one of the
many published tables of binomial probabilities to determine, for sample
of 12 from binomial distributions with \(p = 0.5\) and with
\(p = 0.75\), the probabilities of observing each possible number of
outcomes for each of these values of \(p\). In a two-tail test of the
hypotheses, \(H_0: p = 0.5\) against \(H_1: p = 0.75\) what is the
largest attainable \(P\)-value less than 0.05? What is the critical
region for a test based on this \(P\)-value? What is the power of the
test?

\paragraph{Solution}\label{solution-7}

Below is the table representing the number of successes or each possible
number of outcomes.

\begin{longtable}[]{@{}ccc@{}}
\toprule
\begin{minipage}[b]{0.14\columnwidth}\centering\strut
Outcomes\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\centering\strut
50\%\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\centering\strut
75\%\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
0\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.0002441\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
5.96e-08\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
1\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.00293\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
2.146e-06\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
2\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.01611\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
3.541e-05\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
3\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.05371\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.0003541\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
4\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.1208\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.00239\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
5\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.1934\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.01147\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
6\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.2256\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.04015\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
7\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.1934\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.1032\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
8\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.1208\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.1936\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
9\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.05371\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.2581\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
10\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.01611\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.2323\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
11\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.00293\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.1267\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\centering\strut
12\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.0002441\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering\strut
0.03168\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

Based on these p-values, we can see that the \(P\)-values less than 0.5
are 0 to 2 and 10 to 12. The sum of these is approximately 0.0386,
i.e.~our max \(P\)-value. The power of our test would be obtaining a
result within this critical region, or 1 minus the probability of
obtaining a result outside of it.

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \OperatorTok{-}\StringTok{ }\NormalTok{(}\KeywordTok{pbinom}\NormalTok{(}\DecValTok{9}\NormalTok{, }\DataTypeTok{size =} \DecValTok{12}\NormalTok{, }\DataTypeTok{prob =} \FloatTok{0.75}\NormalTok{) }\OperatorTok{-}\StringTok{ }
\StringTok{       }\KeywordTok{pbinom}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DataTypeTok{size =} \DecValTok{12}\NormalTok{, }\DataTypeTok{prob =} \FloatTok{0.75}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3907126
\end{verbatim}

So the power of this test is approximately 0.391


\end{document}
