---
title: "Chapter Seven"
author: "NAME HERE"
date: "10/9/2017"
header-includes:
   - \usepackage{bbm}
   - \usepackage{bm}
   - \newcommand{\infmat}{\bm{\mathcal{J}}}
   - \usepackage{booktabs}
   - \usepackage{multirow}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise One
#### Question
The numebr of deaths from leukemia and other cancers among survivors of the Hiroshima atom bomb are shown in Table 7.12 (below), classified by the radiation dose received. The data refers to deaths during the period 1950-1959 among survivors who were aged 25 to 64 years in 1950 (from datq set 13 of Cox and Snell 1981, attributed to Otake 1979).

\begin{center}
\begin{tabular}{@{}lcccccc@{}}
\toprule
              & \multicolumn{6}{c}{Radiation Dose (rads)}  \\
Deaths        & 0   & 1-9 & 10-49 & 50-99 & 100-199 & 200+ \\ \midrule
Leukemia      & 13  & 5   & 5     & 3     & 4       & 18   \\
Other Cancers & 378 & 200 & 151   & 47    & 31      & 33   \\ \midrule
Total Cancers & 391 & 205 & 156   & 50    & 35      & 51   \\ \bottomrule
\end{tabular}
\end{center}

#### Solution
**(a)**: Obtain a suitable model to describe the dose-response relationship between radiation and the proportional cancer mortality rates for leukemia.

**(b)**: Exame how well the model describes the data.

**(c)**: Interpret the results.


## Exercise Two
#### Question
**Odds ratios**. Consider a $2\times2$ contingency table from a prospective study in which people who were or were not exposed to some pollutants are followed up and, after several years, categorized according to the presence or absence of a disease. Table 7.13 (below) shows the probabilities for each cell. The odds of disease for either exposure group is $O_i = \pi_i/(1-\pi_i)$, for $i = 1, 2,$ and so the odds ratio
$$
\phi = \frac{O_1}{O_2} = \frac{\pi_1(1-\pi_2)}{\pi_2(1-\pi_1)}
$$
is a measure of the relative likelihood of disease for the exposed and not exposed groups.

\begin{center}
\begin{tabular}{@{}lcc@{}}
\toprule
            & Diseased & Not diseased \\ \midrule
Exposed     & $\pi_1$  & $1-\pi_1$    \\
Not exposed & $\pi_2$  & $1-\pi_2$    \\ \bottomrule
\end{tabular}
\end{center}

#### Solution
**(a)**: For the simple logistic model $\pi_i = e^{\beta_i}/(1+e^{\beta_i})$, show that if there is no difference between the exposed and not exposed groups (i.e. $\beta_1 = \beta_2$), then $\phi = 1$.

**(b)**: Consider $J$ $2\times2$ tables like Table 7.13, one for each level $x_j$ of a factor, such as age group, with $j = 1,...,J$. For the logistic model
$$
\pi_{ij} = \frac{\exp(\alpha_i + \beta_ix_j)}{1 + \exp(\alpha_i + \beta_ix_j)}, \quad i = 1,2, \quad j = 1,...,J.
$$

Show that $\log\phi$ is connstant over all table if $\beta_1 = \beta_2$ (McKinlay 1979).


## Exercise Three
#### Question
Tables 7.14 and 7.15 (both below) show the survival 50 years after graduation of men and women who graduated each year from 1938 and 1947 from various Faculties of the University of Adelaide (data compiled by J.A. Keats). The columns labeled $S$ contain the number of graduates who survived and the columns labeled $T$ contain the total number of graduates. There were insufficient women graduates from the Faculties of Medicine and Engineering to warrant analysis.

\begin{center}
\begin{tabular}{@{}crrrrrrrr@{}}
\toprule
Year       & \multicolumn{8}{c}{Faculty}                                                                                                                                                                   \\
of         & \multicolumn{2}{c}{Medicine}                  & \multicolumn{2}{c}{Arts}                      & \multicolumn{2}{c}{Science}                   & \multicolumn{2}{c}{Engineering}               \\
Graduation & \multicolumn{1}{c}{S} & \multicolumn{1}{c}{T} & \multicolumn{1}{c}{S} & \multicolumn{1}{c}{T} & \multicolumn{1}{c}{S} & \multicolumn{1}{c}{T} & \multicolumn{1}{c}{S} & \multicolumn{1}{c}{T} \\ \midrule
1938       & 18                    & 22                    & 16                    & 30                    & 9                     & 14                    & 10                    & 16                    \\
1939       & 16                    & 23                    & 13                    & 22                    & 9                     & 12                    & 7                     & 11                    \\
1940       & 7                     & 17                    & 11                    & 25                    & 12                    & 19                    & 12                    & 15                    \\
1941       & 12                    & 25                    & 12                    & 14                    & 12                    & 15                    & 8                     & 9                     \\
1942       & 24                    & 50                    & 8                     & 12                    & 20                    & 28                    & 5                     & 7                     \\
1943       & 16                    & 21                    & 11                    & 20                    & 16                    & 21                    & 1                     & 2                     \\
1944       & 22                    & 32                    & 4                     & 10                    & 25                    & 31                    & 16                    & 22                    \\
1945       & 12                    & 14                    & 4                     & 12                    & 32                    & 38                    & 19                    & 25                    \\
1946       & 22                    & 34                    &                       &                       & 4                     & 5                     &                       &                       \\
1947       & 28                    & 37                    & 13                    & 23                    & 25                    & 31                    & 25                    & 35                    \\
Total      & 177                   & 275                   & 92                    & 168                   & 164                   & 214                   & 103                   & 142                   \\ \bottomrule
\end{tabular}

\begin{tabular}{@{}crrrr@{}}
\toprule
Year       & \multicolumn{4}{c}{Faculty}                                                                   \\
of         & \multicolumn{2}{c}{Arts}                      & \multicolumn{2}{c}{Science}                   \\
Graduation & \multicolumn{1}{c}{S} & \multicolumn{1}{c}{T} & \multicolumn{1}{c}{S} & \multicolumn{1}{c}{T} \\ \midrule
1938       & 14                    & 19                    & 1                     & 1                     \\
1939       & 11                    & 16                    & 4                     & 4                     \\
1940       & 15                    & 18                    & 6                     & 7                     \\
1941       & 15                    & 21                    & 3                     & 3                     \\
1942       & 8                     & 9                     & 4                     & 4                     \\
1943       & 13                    & 13                    & 8                     & 9                     \\
1944       & 18                    & 22                    & 5                     & 5                     \\
1945       & 18                    & 22                    & 16                    & 17                    \\
1946       & 1                     & 1                     & 1                     & 1                     \\
1947       & 13                    & 16                    & 10                    & 10                    \\
Total      & 126                   & 157                   & 58                    & 61                    \\ \bottomrule
\end{tabular}
\end{center}



#### Solution
**(a)**: Are the proportions of graduates who survived for 50 years after graduation the same all years of graduation?

**(b)**: Are the proportions of male graduates who survived for 50 years after graduation the same for all Faculties?

**(c)**: Are the proportions of female graduates who survived for 50 years after graduation the same for Arts and Science?

**(d)**: Is the difference between men and women in the proportion of graduates who survived for 50 years after graduation the same for Arts and Science?